all:
	g++ jrsa.cpp RSAEngine.h RSAEngine.cpp Base64Codec.h Base64Codec.cpp RSAPrivateKey.h RSAPrivateKey.cpp KeyFileManager.h KeyFileManager.cpp berUtils.h berUtils.cpp RSAKeyGen.h RSAKeyGen.cpp -lgmp -lgmpxx -o jrsa
clean:
	rm jrsa
